import { Geist, Geist_Mono, Bebas_Neue } from "next/font/google";
import "./globals.css";
import { Navbar, Footer, ClientLayout } from "@/components/layout";
import UserContextProvider from "@/context/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
  variable: "--babas-neue",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "NÓMADA - Luxury Handbags",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bebasNeue.variable} antialiased`}
      >
        <UserContextProvider value={{ user: null }}>
          <ClientLayout>{children}</ClientLayout>
        </UserContextProvider>
      </body>
    </html>
  );
}
